# Generated by Django 2.2.6 on 2019-10-29 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('payment_method', models.TextField(default='paytm')),
                ('status', models.BooleanField(default=False)),
                ('date_requested', models.DateTimeField(auto_now_add=True, verbose_name='date requested')),
                ('date_confirmed', models.DateTimeField(null=True, verbose_name='date confirmed')),
                ('user_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_user_1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_user_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
