# Generated by Django 2.2.6 on 2019-10-30 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('message_sent', models.DateTimeField(auto_now_add=True, verbose_name='message_sent')),
                ('user_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_send', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
